<?php
    $authors = $this->authors;
    $one = 1 === count($authors);
?>    
<div class="authors">
<?php foreach ($authors as $author): ?>        
    <div class="author">
    <?php if (!$one || $this->collapsed || $author->getRole() !== \Application\Utils\AuthorRole::AUTHOR): ?>
        <?php 
            switch ($author->getRole()) {
                case \Application\Utils\AuthorRole::REWRITE_AUTHOR:
                    $glyph = "glyphicon-erase";
                    $hint = "Rewrite author";
                    break;
                case \Application\Utils\AuthorRole::TRANSLATOR:
                    $glyph = "glyphicon-globe";
                    $hint = "Translator";
                    break;
                default: /*\Application\Utils\AuthorRole::AUTHOR*/
                    $glyph = "glyphicon-pencil";
                    $hint = "Author";
                    break;
            }
        ?>
        <span class="glyphicon <?php echo $glyph; ?>" aria-label="<?php echo $hint; ?>" title="<?php echo $hint; ?>"></span>
    <?php endif; ?>        
    <?php
        echo $this->partial('partial/user.phtml', ['user' => $author->getUser()]);
    ?>
    </div>
<?php endforeach; ?>
</div>