<?php 
    $members = $this->members;
    $columns = array(
        'User' => \Application\Utils\DbConsts\DbViewMembership::DISPLAYNAME,
        'Votes' => \Application\Utils\DbConsts\DbViewMembership::VOTES,
        'Revisions' => \Application\Utils\DbConsts\DbViewMembership::REVISIONS,
        'Pages' => \Application\Utils\DbConsts\DbViewMembership::PAGES,
        'Joined' => \Application\Utils\DbConsts\DbViewMembership::JOINDATE,
    );
?>

<table class="table table-striped 
    <?php 
        if ($this->preview) {
            echo "table-preview";
        } else {
            echo "table-sortable";             
        } 
    ?>
    "
>
    <tr>
        <?php foreach ($columns as $text => $name): ?>
        <th 
            data-name="<?php echo $name; ?>" 
            <?php 
                if ($this->orderBy === $name) {
                    echo 'data-ascending="'.$this->ascending.'" ';
                    echo 'class="ordered"';
                } 
            ?>
        >
            <?php 
                echo $text; 
                if ($this->orderBy === $name) {
                    if ($this->ascending) {
                        echo "&nbsp;&UpArrow;";
                    } else {
                        echo "&nbsp;&DownArrow;";
                    }
                }
            ?>            
        </th>           
        <?php endforeach;?>
    </tr>    
    <?php foreach ($members as $user): ?>
    <tr>
        <td><a href="#"><?php echo $user->getDisplayName(); ?></a></td>                                                
        <td><?php echo $user->getVoteCount(); ?></td>
        <td><?php echo $user->getRevisionCount(); ?></td>
        <td><?php echo $user->getPageCount(); ?></td>
        <td><?php echo $user->getMembership()[$this->siteId]->format('Y-m-d'); ?></td>
    </tr>
    <?php endforeach; ?>
</table>
<?php 
    if (!$this->preview) {
        echo $this->paginationControl($members, 'Sliding', 'partial/paginator'); 
    }
?>