<nav class="navbar navbar-inverse navbar-fixed-top scpper-navbar" role="navigation">
    <div class="navbar-header">         
        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="ScpperDB" height="50px"/>
            <span class="navbar-header-name">&nbsp;ScpperDB</span>
        </a>
    </div>    
    <div class="collapse navbar-collapse">      
        <ul class="nav navbar-nav">
        <?php foreach ($this->container as $page) { ?>
            <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
            <?php // when using partials we need to manually check for ACL conditions ?>
            <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
            <?php $hasChildren = $page->hasPages(); ?>
            <?php if (!$hasChildren) { ?>
                <li <?php if ($page->isActive()):?> class="active" <?php endif; ?>>
                    <a href="<?php echo $page->getHref() ?>">
                        <?php echo $this->translate($page->getLabel()) ?>
                    </a>
                </li>
            <?php } else { ?>
            <li class="dropdown <?php if ($page->isActive()):?> active <?php endif; ?>">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate($page->getLabel()) ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child) { ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                        <li <?php if ($child->isActive()):?> class="active" <?php endif; ?> >
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </li>
            <?php } ?>
        <?php } ?>
        </ul>      
    </div>
    <form class="scpper-navbar-search" method="POST" role="search" action="/search">
        <div class="input-group">
            <input type="text" name="search-text" id="search-text" class="form-control search-control" placeholder="Page or user..." value="">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-default" aria-label="Go">
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
        </div>
    </form>      
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>    
</nav>