<?php if ($this->pageCount): ?>
<nav class="text-center table-navigation">
    <ul class="pagination table-pagination">
        <?php if ((int) $this->pageCount > 1): ?>
        <!-- First page link -->
        <li class="text-condensed">
            <?php if ($this->current !== 1): ?>
                <a data-page="1" href="javascript:;">
                    &lt;&lt;
                </a>
            <?php else: ?>
            <span class="disabled">&lt;&lt;</span>
            <?php endif; ?>
        </li>
        <!-- Previous page link -->
        <li>
            <?php if (isset($this->previous)): ?>
                <a data-page="<?php echo $this->previous ?>" href="javascript:;">
                    &lt;
                </a>
            <?php else: ?>
              <span class="disabled">&lt;</span>
            <?php endif; ?>
        </li>
        <!-- Numbered page links -->        
        <?php $maxDiff = max($this->current-$this->firstPageInRange, $this->lastPageInRange-$this->current); ?>
        <?php foreach ($this->pagesInRange as $page): ?>
        <?php 
            $diff = abs($page-$this->current)/$maxDiff;
            if ($diff >= 0.5) {
                $class = "pagination-hidden-sm";
            } else if ($diff > 0.2) {
                $class = "pagination-hidden-xs";
            } else {
                $class = null;
            }
        ?>        
        <li <?php if ($class) { echo 'class="'.$class.'"'; } ?> >
          <?php if ($page != $this->current): ?>
            <a data-page="<?php echo $page ?>" href="javascript:;">
                <?php echo $page; ?>
            </a>
          <?php else: ?>
            <input type="tel" pattern="[0-9]*" inputmode="numeric" min="1" max="<?php echo $this->last; ?>" size="1" class="form-control table-pagination-input text-center" value="<?php echo $page; ?>">
          <?php endif; ?>
        </li>
        <?php endforeach; ?>
        <!-- Next page link -->
        <li>
            <?php if (isset($this->next)): ?>
              <a data-page="<?php echo $this->next ?>" href="javascript:;">
                &gt;
              </a>
            <?php else: ?>
              <span class="disabled">&gt;</span>
            <?php endif; ?>
        </li>
        <!-- Last page link -->
        <li class="text-condensed">
            <?php if ($this->current !== $this->last): ?>
              <a data-page="<?php echo $this->last ?>" href="javascript:;">
                &gt;&gt;
              </a>
            <?php else: ?>
              <span class="disabled">&gt;&gt;</span>
            <?php endif; ?>
        </li>
        <?php endif; ?>
        <!-- Entries per page selector -->
    </ul>
    <?php if ($this->totalItemCount > 10): ?>
    <div class="per-page-block form-inline">
        <label for="perPage" class="control-label">Show</label>
        <select class="form-control per-page-control" name="perPage">
            <?php $pageSizes = array(10, 25, 50, 100); ?>
            <?php foreach ($pageSizes as $size): ?>
            <option <?php if ($size === $this->itemCountPerPage) {echo "selected";} ?> >
                <?php echo $size ?>
            </option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php endif; ?>
</nav>
<?php endif; ?>