<?php $this->headTitle('Reports'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#report-list', '/admin/reportList', {});
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<h3>Reports</h3>
<div class="table-container" id="report-list">
<?php
$table = $this->table;

echo $this->partial(
    'partial/tables/default/table.phtml', 
    [
        'table' => $table,        
    ]
);    
?>
</div>
