<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#user-list', '/users/userList', {siteId: <?php echo $this->site->getWikidotId();?>});
        scpper.tables.assignPaginatorEvents('#author-list', '/users/authorList', {siteId: <?php echo $this->site->getWikidotId();?>});
    }

    $(document).ready(init);
    
}());

<?php $this->headScript()->captureEnd(); ?>
<span class="h1">
    <a href="<?php echo $this->site->getUrl(); ?>">
       <?php echo $this->site->getEnglishName(); ?>
    </a>        
</span>
<h3>Users (<?php echo $this->usersTable->getPaginator()->getTotalItemCount();?> total)</h3>
<div class="table-container" id="user-list">
<?php

$usersTable = $this->usersTable;

echo $this->partial(
    'partial/tables/table.phtml', 
    array(
        'table' => $usersTable,
        'data' => array('siteId' => $this->site->getWikidotId()),
    )
);    
?>
</div>
<h3>Authors (<?php echo $this->authorsTable->getPaginator()->getTotalItemCount();?> total)</h3>            
<div class="table-container" id="author-list">
<?php

$authorsTable = $this->authorsTable;

echo $this->partial(
    'partial/tables/table.phtml', 
    array(
        'table' => $authorsTable,
    )
);    
?>
</div>