<?php $this->headTitle('2018'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {
        
    var timelapse = null;
    var framelen = 3*60*60*1000; // ms
    var lastpage = 0;
    var curtime = 0;
    var canvas = null; // document.getElementById("mainlist-timelapse");
    var context = null; //canvas.getContext('2d', { alpha: false });        
    var fillfull = 'green';
    var fillempty = 'black';
    var filldeleted = 'red';
    var perrow = 50;
    var cellsize = 10;
    
    function draw() 
    {   
        curtime.setMilliseconds(curtime.getMilliseconds()+framelen);    
        context.save()
        context.fillStyle = 'white';
        context.fillRect(0, 0, 549, 50);
        context.font = '24px Helvetica';
        context.fillStyle = 'black';
        context.textAlign = 'center';
        context.fillText(curtime.format('mmmm yyyy'), 275, 42);
        context.translate(0, 50)
        while (lastpage<timelapse.length && timelapse[lastpage].t <= curtime) {
            r = Math.floor(timelapse[lastpage].n/perrow);
            c = timelapse[lastpage].n%perrow;
            if (timelapse[lastpage].d)
                context.fillStyle = filldeleted
            else
                context.fillStyle = fillfull;
            context.fillRect(c*(cellsize+1), r*(cellsize+1), cellsize, cellsize);
            lastpage++;
        }
        context.restore();
        if (lastpage < timelapse.length)
            window.requestAnimationFrame(draw);
    }
    
    function init()
    {
        canvas = document.getElementById("mainlist-timelapse");
        context = canvas.getContext('2d', { alpha: false });                    
        context.save()
        context.fillStyle = 'white';
        context.fillRect(0, 0, 549, 50);
        context.translate(0, 50)                
        context.fillRect(0, 220, 549, 20);
        context.font = '12px serif';
        context.fillStyle = fillempty;
        context.fillRect(10, 225, cellsize, cellsize);
        context.fillText(" - empty", 23, 234);
        context.fillStyle = fillfull;
        context.fillRect(100, 225, cellsize, cellsize);
        context.fillText(" - full", 113, 234);
        context.fillStyle = filldeleted;
        context.fillRect(175, 225, cellsize, cellsize);
        context.fillText(" - deleted", 188, 234);        
        context.restore()
        $.getJSON( "/data/2018.json", function( data ) {
            timelapse = [];
            for (var d in data) {
                var a = {
                    n: Number(data[d].n)-3000,
                    t: scpper.convertDate(data[d].t),
                    d: data[d].d
                }
                timelapse.push(a);
            }           
            curtime = timelapse[1].t;
            window.requestAnimationFrame(draw);
        });        
    }        

    $(document).ready(init);
}());

<?php $this->headScript()->captureEnd(); ?>
<div class="row">
    <div class="col-md-offset-2 col-md-8 text-center">
        <h1>Series 4</h1>
        <canvas id="mainlist-timelapse" width="549" height="289">

        </canvas>
    </div>
</div>
