<?php $this->headTitle('2018'); ?>
<?php $this->headScript()->appendFile('/js/scpper_roundup.js'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {
        
    function init()
    {
        hideShowTimelapseButton = function (visible) {
            if (scpper.roundup.seriesTimelapse.isPlaying()) 
                document.getElementById("timelapse-state").hidden = !visible;
        };
    
        scpper.roundup.seriesTimelapse.init("mainlist-timelapse", "timelapse-state", "/data/series-4-timelapse.json");
        $("#mainlist-timelapse-cover").on('mouseenter', function () { hideShowTimelapseButton(true); });
        $("#mainlist-timelapse-cover").on('mouseleave', function () { hideShowTimelapseButton(false); });
        $("#timelapse-state").on('click', function () { scpper.roundup.seriesTimelapse.switch(); });
    }        

    $(document).ready(init);
}());

<?php $this->headScript()->captureEnd(); ?>
<div class="row">
    <div class="col-md-offset-2 col-md-8 text-center">
        <h1>Series 4 timelapse</h1>
        <div id="mainlist-timelapse-cover">
            <canvas id="mainlist-timelapse" width="549" height="289">
                lol fuck old browsers
            </canvas>
            <img id="timelapse-state" src="img/play-btn.png">
        </div>
    </div>
</div>
