<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#editor-list', '/revisions/editorList', {siteId: <?php echo $this->site->getWikidotId();?>});
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<span class="h1">
    <a href="<?php echo $this->site->getUrl(); ?>">
       <?php echo $this->site->getEnglishName(); ?>
    </a>        
</span>
<p class="small-text">Updated <?php echo $this->site->getLastUpdate()->format('Y-m-d H:i'); ?></p>
<h3>Editors (<?php echo $this->table->getPaginator()->getTotalItemCount();?> total)</h3>
<div class="table-container" id="editor-list">
<?php
$table = $this->table;

echo $this->partial(
    'partial/tables/table.phtml', 
    array(
        'table' => $table,
        'data' => array(
            'total' => $this->total
        )
    )
);    
?>
</div>