<?php $this->headTitle('Revisions'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#editor-list', '/revisions/editorList', {siteId: <?php echo $this->site->getId();?>});
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<span class="h1">
    <?php echo $this->partial('partial/site.phtml', ['site' => $this->site, 'link' => true]);?>
</span>
<?php if ($site->getLastUpdate()): ?>
<p class="small-text">
    Updated <?php echo $site->getLastUpdate()->format('Y-m-d H:i'); ?>
</p>
<?php endif; ?>
<h3>Editors (<?php echo $this->table->getPaginator()->getTotalItemCount();?> total)</h3>
<div class="table-container" id="editor-list">
<?php
$table = $this->table;

echo $this->partial(
    'partial/tables/default/table.phtml', 
    [
        'table' => $table,
        'data' => [
            'total' => $this->total
        ]
    ]
);    
?>
</div>