<?php 
$this->headTitle('Tags');
$this->headScript()->appendFile('/js/bootstrap-switch.js');
$this->headScript()->captureStart(); 

?>
// Anonymous self-executing function not to clutter global scope with temporary stuff
(function() {

    function initElements()
    {
        $('#combine-with-and').prop('checked', <?php echo $this->method==='and'?'true':'false'; ?>);
        <?php foreach ($this->searchTags as $tag): ?>
        scpper.tags.addSearchTag('<?php echo $tag; ?>');
        <?php endforeach; ?>
    }
    
    function init()
    {           
        var tags = [
            <?php 
            $i=0;
            foreach ($this->tags as $tag) {
                if ($i > 0) {
                    echo ',';
                }            
                vprintf('{tag: "%s", count: "%d", label: "%s"}', [strtolower($tag->getTag()), $tag->getPageCount(), htmlspecialchars_decode(strtolower($tag->getTag()))]);
                $i++;
            }
            ?>
        ];    
        scpper.tags.init(tags, '#tags', '#combine-with-and', '#search-tags', '#prototype-tag-element');
        $('#tags').autocomplete({
          source: scpper.tags.autocompleteTag,
          response: scpper.tags.processAutocompleteResponse,
          select: scpper.tags.addSelectedTag,          
        })
        .on('keyup', scpper.tags.tagKeyUp);
        
        $('#prototype-tag-element .search-tag-body').on('click', scpper.tags.bodySearchTagClick);
        $('#prototype-tag-element .search-tag-delete').on('click', scpper.tags.deleteSearchTagClick);
        $('#button-go').on('click', scpper.tags.submit);
        initElements();
        $('#combine-with-and').bootstrapSwitch({
            on: 'All', 
            off: 'Any', 
            same: true, 
            size: 'xs',
            offClass: 'primary'
        });
        scpper.tables.assignPaginatorEvents('#page-list', '/tags/pageList', {
            siteId: <?php echo $this->siteId;?>,
            method: scpper.tags.buildMethodString(),
            tags: scpper.tags.buildTagsString()
        });        
    }
    $(document).ready(init);

}());

<?php $this->headScript()->captureEnd(); ?>

<div class="form-horizontal tags-search-form">
    <label for="tags">Tags</label>
    <div class="input-group">        
        <input type="text" class="form-control" id="tags" placeholder="Example: scp memetic -joke">        
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default" id="button-go" aria-label="Go">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
        </span>
    </div>    
    <div class="tags-search-options">
        <div class="tags-combine-method">
            <input type="checkbox" id="combine-with-and">
        </div>
        <a href="/tags" class="btn btn-default btn-xs tags-" style="margin-right: 5px">Reset</a>
        <div id="search-tags" style="display: inline"></div>          
    </div>
</div>

<div class="table-container" id="page-list">
<?php
$table = $this->table;
if ($table) {
    echo $this->partial(
        'partial/tables/default/table.phtml', 
        array(
            'table' => $table,
            'data' => array(
                'siteId' => $this->siteId,
                
            ),
        )
    );    
}
?>
</div>

<div hidden="1">
<div id="prototype-tag-element" class="search-tag-container" data-tag="" data-include="1">
<span class="search-tag search-tag-body" title="Include/exclude tag">memetic</span>
<span class="search-tag search-tag-delete" title="Remove tag">&#x2716</span>
</div>
</div>