<?php $this->headTitle('Votes'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#voter-list', '/votes/voterList', {siteId: <?php echo $this->site->getId();?>});
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<span class="h1">
    <?php echo $this->partial('partial/site.phtml', array('site' => $this->site, 'link' => true));?>   
</span>
<p class="small-text">Updated <?php echo $this->site->getLastUpdate()->format('Y-m-d H:i'); ?></p>
<h3>Voters (<?php echo $this->table->getPaginator()->getTotalItemCount();?> total)</h3>
<div class="table-container" id="voter-list">
<?php
$table = $this->table;

echo $this->partial(
    'partial/tables/table.phtml', 
    array(
        'table' => $table,
        'data' => array(
        )
    )
);    
?>
</div>