<?php $this->headTitle('Search'); ?>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('search'));
    $queryField = $form->get(\Application\Form\SearchForm::TEXT_FIELD_NAME);
    $siteField = $form->get(\Application\Form\SearchForm::SITE_FIELD_NAME);
    $siteField->setValue($this->querySiteId);
    $form->prepare();
    $currentSiteId = $this->site->getId();
    $searchForCurrent = (int)$this->querySiteId===$currentSiteId;
?>

<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {
    
    var siteId = <?php echo $currentSiteId; ?>;
    var paginatorData = {
        siteId: <?php echo $currentSiteId; ?>,
        query: "<?php echo $queryField->getValue(); ?>",        
        page: 1, 
        perPage: 10
    };
    
    function init()
    {
        scpper.tables.assignPaginatorEvents('#page-list', 
            '/search/pageList', 
            {
                siteId: paginatorData.siteId,
                query: paginatorData.query,
                withDeleted: <?php echo (int)$form->get(\Application\Form\SearchForm::ALL_BRANCHES_NAME)->isChecked(); ?>,
                allBranches: <?php echo (int)$form->get(\Application\Form\SearchForm::WITH_DELETED_NAME)->isChecked(); ?>
            }
        );
        scpper.tables.assignPaginatorEvents('#user-list', 
            '/search/userList', 
            {
                siteId: paginatorData.siteId,
                query: paginatorData.query,
                withDeleted: <?php echo (int)$form->get(\Application\Form\SearchForm::ALL_BRANCHES_NAME)->isChecked(); ?>,
                allBranches: <?php echo (int)$form->get(\Application\Form\SearchForm::WITH_DELETED_NAME)->isChecked(); ?>                
            }
        );        
        $('#switch-query-sites').on('click', switchSites);
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Search</h2>
        <?php echo $this->form()->openTag($form); ?>
        <div class="input-group" id="search-group-main">
        <?php echo $this->formElement($queryField); ?>
            <span class="input-group-btn" id="search-group-main-button">
                <?php echo $this->formElement($form->get(\Application\Form\SearchForm::BUTTON_NAME)); ?>
            </span>            
        </div>
        <?php echo $this->formElement($form->get(\Application\Form\SearchForm::SITE_FIELD_NAME)); ?>
        <br>
        <div class="search-options">
            <label class="checkbox-inline">            
            <?php echo $this->formElement($form->get(\Application\Form\SearchForm::ALL_BRANCHES_NAME)); ?>All branches
            </label>
            <label class="checkbox-inline">
            <?php echo $this->formElement($form->get(\Application\Form\SearchForm::WITH_DELETED_NAME)); ?>With deleted
            </label>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php if ($queryField->getValue() !== ''): ?>
    <?php $this->headTitle('"'.$queryField->getValue().'"'); ?>
    <?php if ($this->pages): ?>
        <h3>Pages</h3>
        <div class="table-container" id="page-list">
        <?php

        echo $this->partial(
            'partial/tables/default/table.phtml', 
            [
                'table' => $this->pages,
                'data' => ['siteId' => $this->site->getId()],
            ]
        );    
        ?>
        </div>       
    <?php endif; ?>
    <?php if ($this->users): ?>
        <h3>Users</h3>
        <div class="table-container" id="user-list">
        <?php

        echo $this->partial(
            'partial/tables/default/table.phtml', 
            [
                'table' => $this->users,
                'data' => ['siteId' => $this->site->getId()],
            ]
        );    
        ?>
        </div>  
    <?php endif; ?>
<?php endif; ?>