<?php $this->headTitle('Search'); ?>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('search'));
    $field = $form->get(\Application\Form\SearchForm::TEXT_FIELD_NAME);
    $form->prepare();
?>

<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {
    
    var siteId = <?php echo $this->site->getId(); ?>;
    var paginatorData = {
        siteId: "all",
        query: "<?php echo $field->getValue(); ?>",
        page: 1, 
        perPage: 10
    };
    
    function switchSites(event)
    {
        scpper.tables.fetchPaginator("#page-list", "/search/pageList", paginatorData);
        scpper.tables.fetchPaginator("#user-list", "/search/userList", paginatorData);
        if (paginatorData.siteId === "all") {
            event.target.text="Current branch";
            paginatorData.siteId = siteId;
        } else {
            event.target.text="All branches";
            paginatorData.siteId = "all";
        }
    }

    function init()
    {

        scpper.tables.assignPaginatorEvents('#page-list', 
            '/search/pageList', 
            {
                siteId: <?php echo $this->site->getId();?>,
                query: "<?php echo $field->getValue(); ?>"
            }
        );
        scpper.tables.assignPaginatorEvents('#user-list', 
            '/search/userList', 
            {
                siteId: <?php echo $this->site->getId();?>,
                query: "<?php echo $field->getValue(); ?>"
            }
        );        
        $('#all-site-pages').on('click', switchSites);
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
        <h2>Search</h2>
        <?php echo $this->form()->openTag($form); ?>
        <div class="input-group">
        <?php echo $this->formElement($field); ?>
            <span class="input-group-btn">
        <?php echo $this->formElement($form->get(\Application\Form\SearchForm::BUTTON_NAME)); ?>
            </span>            
            &nbsp;&nbsp;
            <a class="btn btn-default input-group-btn" id="all-site-pages" href="javascript:;" role="button">All branches</a>
        </div>             
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php if ($field->getValue() !== ''): ?>
    <?php $this->headTitle('"'.$field->getValue().'"'); ?>
    <h3>Pages</h3>
    <div class="table-container" id="page-list">
    <?php

    echo $this->partial(
        'partial/tables/table.phtml', 
        array(
            'table' => $this->pages,
            'data' => array('siteId' => $this->site->getId()),
        )
    );    
    ?>
    </div>       
    <h3>Users</h3>
    <div class="table-container" id="user-list">
    <?php

    echo $this->partial(
        'partial/tables/table.phtml', 
        array(
            'table' => $this->users,
            'data' => array('siteId' => $this->site->getId()),
        )
    );    
    ?>
    </div>  
<?php endif; ?>