<?php $this->headTitle('Search'); ?>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('search'));
    $queryField = $form->get(\Application\Form\SearchForm::TEXT_FIELD_NAME);
    $siteField = $form->get(\Application\Form\SearchForm::SITE_FIELD_NAME);
    $siteField->setValue($this->querySiteId);
    $form->prepare();
    $currentSiteId = $this->site->getId();
    $searchForCurrent = (int)$this->querySiteId===$currentSiteId;
?>

<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {
    
    var siteId = <?php echo $currentSiteId; ?>;
    var paginatorData = {
        siteId: <?php echo $searchForCurrent?$currentSiteId:'"all"'; ?>,
        query: "<?php echo $queryField->getValue(); ?>",
        page: 1, 
        perPage: 10
    };
    
    function switchSites(event)
    {
        <?php if ($searchForCurrent): ?>            
            scpper.post('/search', {"search-site-id": "all", "search-text": paginatorData.query});
        <?php else: ?>
            scpper.post('/search', {"search-site-id": siteId, "search-text": paginatorData.query});
        <?php endif; ?>
    }

    function init()
    {

        scpper.tables.assignPaginatorEvents('#page-list', 
            '/search/pageList', 
            {
                siteId: paginatorData.siteId,
                query: paginatorData.query
            }
        );
        scpper.tables.assignPaginatorEvents('#user-list', 
            '/search/userList', 
            {
                siteId: paginatorData.siteId,
                query: paginatorData.query
            }
        );        
        $('#switch-query-sites').on('click', switchSites);
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2>Search</h2>
        <?php echo $this->form()->openTag($form); ?>
        <div class="input-group" id="search-group-main">
        <?php echo $this->formElement($queryField); ?>
            <span class="input-group-btn" id="search-group-main-button">
                <?php echo $this->formElement($form->get(\Application\Form\SearchForm::BUTTON_NAME)); ?>
            </span>            
        </div>
        <a class="btn btn-default" id="switch-query-sites" href="javascript:;" role="button">
            <?php if ($searchForCurrent): ?>
            <span class="glyphicon glyphicon-globe"></span><span class="switch-search-sites-caption" aria-label="All branches"> All branches</span>
            <?php else: ?>
            <span class="glyphicon glyphicon-home"></span><span class="switch-search-sites-caption" aria-label="Current branche"> Current branch</span>
            <?php endif; ?>
        </a>        
        <?php echo $this->formElement($form->get(\Application\Form\SearchForm::SITE_FIELD_NAME)); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
<?php if ($queryField->getValue() !== ''): ?>
    <?php $this->headTitle('"'.$queryField->getValue().'"'); ?>
    <?php if ($this->pages): ?>
        <h3>Pages</h3>
        <div class="table-container" id="page-list">
        <?php

        echo $this->partial(
            'partial/tables/default/table.phtml', 
            array(
                'table' => $this->pages,
                'data' => array('siteId' => $this->site->getId()),
            )
        );    
        ?>
        </div>       
    <?php endif; ?>
    <?php if ($this->users): ?>
        <h3>Users</h3>
        <div class="table-container" id="user-list">
        <?php

        echo $this->partial(
            'partial/tables/default/table.phtml', 
            array(
                'table' => $this->users,
                'data' => array('siteId' => $this->site->getId()),
            )
        );    
        ?>
        </div>  
    <?php endif; ?>
<?php endif; ?>