<?php $page = $this->page; ?>
<?php $this->headTitle($this->escapeHtml($page->getTitle())); ?>
<?php
$this->headScript()->appendFile('/js/scpper_charts.js');
$this->headScript()->appendFile('/js/scpper_reports.js');
$this->headScript()->appendFile('https://www.gstatic.com/charts/loader.js');
?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    // Initialize global variables
    var pageId = <?php echo $page->getId() ?>;

    function init()
    {
        var dialog = scpper.reports.initReportDialog('#report-dialog', false);
        scpper.tables.assignPaginatorEvents('#revision-list', '/page/revisionList', {pageId: pageId});
        scpper.tables.assignPaginatorEvents('#vote-list', '/page/voteList', {pageId: pageId});        
        $('#show-report').click(
            function() {
                dialog.dialog("open");
            }
        );
                
    }

    $(document).ready(init);    
    
    // Call google graphing API
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(function () {
        scpper.charts.rating.go('/page/ratingChart', {pageId: pageId}, 'page-rating-chart');
    });

}());

<?php $this->headScript()->captureEnd(); ?>

<p>
    <span class="h2">
        <a href="<?php printf("%s/%s", $page->getSite()->getUrl(), $page->getName())?>">
            <?php echo $this->escapeHtml($page->getTitle()); ?>
        </a>
    </span>
    <br>
    on
    <?php echo $this->partial('partial/site.phtml', array('site' => $page->getSite(), 'link' => true));?>
    <br>
    <span class="small-text">
        Updated <?php echo $page->getSite()->getLastUpdate()->format('Y-m-d H:i') ?>
    </span>
</p>
<hr>
<div id="page-top">
    <div id="page-summary">
        <?php if ($page->getAltTitle()): ?>
        Alternative title: <strong><?php echo $this->escapeHtml($page->getAltTitle()); ?></strong>
        <br>
        <?php endif; ?>
        Posted: <strong><?php echo $page->getCreationDate()->format('Y-m-d H:i') ?></strong>
        <br>
        Contributors:
        <strong>
            <?php $authors = $page->getAuthors(); ?>
            <?php if (!$authors || count($authors)===0): ?>
                <em>Unknown</em>
            <?php else: ?>
                <?php
                    $one = 1 === count($authors);
                    $i = 0;
                ?>
                <?php foreach ($authors as $author): ?>
                    <?php echo $this->partial('partial/user.phtml', array('user' => $author->getUser())); ?>
                    <?php
                        if (!$one || $author->getRole() !== \Application\Utils\AuthorRole::AUTHOR) {
                            printf("(%s)", \Application\Utils\AuthorRole::getDescription($author->getRole()));
                        }
                        if (!$one && $i<count($authors)-1) {
                            echo ', ';

                        }
                    ?>
                    <?php $i++; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </strong>
        <br>
        <?php
            $cleanPos = 0; $cleanNeg = 0;
            $contribPos = 0; $contribNeg = 0;
            $adjPos = 0; $adjNeg = 0;
            foreach ($page->getVotes() as $vote) {
                if ($vote->getFromMember()) {
                    if ($vote->getValue() > 0) {
                        $cleanPos++;
                    } else {
                        $cleanNeg--;
                    }
                }
                if ($vote->getFromContributor()) {
                    if ($vote->getValue() > 0) {
                        $contribPos++;
                    } else {
                        $contribNeg--;
                    }
                }
                if ($vote->getFromActive()) {
                    if ($vote->getValue() > 0) {
                        $adjPos++;
                    } else {
                        $adjNeg--;
                    }
                }
            }
        ?>
        Rating: <strong><?php echo $page->getCleanRating(); ?> (<?php printf('%+d / %d', $cleanPos, $cleanNeg) ?>)</strong>
        <br>
        Contributor rating: <strong><?php echo $page->getContributorRating(); ?> (<?php printf('%+d / %d', $contribPos, $contribNeg) ?>)</strong>
        <br>
        Adjusted rating: <strong><?php echo $page->getAdjustedRating(); ?> (<?php printf('%+d / %d', $adjPos, $adjNeg) ?>)</strong>
        <br>
        Rank: <strong>#<?php echo $page->getRank()+1 ?></strong>
        <br>
        Status: <strong><?php echo \Application\Utils\PageStatus::getDescription($page->getStatus()); ?></strong>
        <br>
        Kind: <strong><?php echo \Application\Utils\PageKind::getDescription($page->getKind()); ?></strong>
        <br>
        <button id="show-report" href="javascript:;" class="btn btn-danger">Found an error?</button>
    </div>
    <div id="page-chart">
        <div class="chart-container" id="page-rating-chart">
        </div>
    </div>    
</div>
<?php if ($page->getStatus() === \Application\Utils\PageStatus::ORIGINAL): ?>
    <?php if (count($page->getTranslations()) > 0): ?>
    Translations of this page:
    <ul>
        <?php foreach ($page->getTranslations() as $trans): ?>
        <li>
            <?php echo $this->partial('partial/page.phtml', array('page' => $trans)); ?>
            on
            <em>
                <?php echo $this->partial('partial/site.phtml', array('site' => $trans->getSite(), 'link' => false));?>
            </em>
            by
            <em>
                <?php $i=0; foreach ($trans->getAuthors() as $auth): ?>
                    <?php if ($i>0): ?>, <?php endif; ?>
                    <?php echo $this->partial('partial/user.phtml', array('user' => $auth->getUser())); ?>
                <?php $i++; endforeach; ?>
            </em>
            at
            <em>
                <?php echo sprintf('%+d', $trans->getCleanRating()) ?>
            </em>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <br>
    <?php endif; ?>
<?php else: ?>
    <?php $orig = $page->getOriginal(); ?>
    <?php if ($orig !== null): ?>
        <strong>Original page:</strong>
        <?php echo $this->partial('partial/page.phtml', array('page' => $orig)); ?>
        on
        <em>
            <?php echo $this->partial('partial/site.phtml', array('site' => $orig->getSite(), 'link' => false));?>
        </em>
        by
        <em>
            <?php $i=0; $one=count($orig->getAuthors())===1; foreach ($orig->getAuthors() as $auth): ?>
                <?php if ($i>0): ?>, <?php endif; ?>
                <?php echo $this->partial('partial/user.phtml', array('user' => $auth->getUser())); ?>                        
                <?php if (!$one || $auth->getRole() !== \Application\Utils\AuthorRole::AUTHOR) {
                  printf('(%s)', \Application\Utils\AuthorRole::getDescription($auth->getRole())); }
                ?>
            <?php $i++; endforeach; ?>
        </em>
        at
        <em>
            <?php echo sprintf('%+d', $orig->getCleanRating()) ?>
        </em>
    <?php else: ?>
        Original page not found
    <?php endif; ?>
    <br>
<?php endif; ?>
<?php 
    $tags = $page->getTags();
    if (count($tags) > 0):
?>
    <strong>Tags</strong>: <em>
        <?php for ($j=0; $j<count($tags); $j++): ?>
            <a href="/tags?tags=<?php echo urlencode($tags[$j]);?>" ><?php echo $this->escapeHtml($tags[$j]); ?></a><?php if ($j < count($tags)-1) {echo ',';}?>
        <?php endfor; ?>
    </em>
<?php endif; ?>
<hr>
<h4><?php echo $this->page->getRevisionCount();?> revisions</h4>
<div class="table-container" id="revision-list">
<?php
$revTable = $this->revisions;

echo $this->partial(
    'partial/tables/default/table.phtml',
    array(
        'table' => $revTable,
        'data' => array(),
    )
);
?>
</div>
<?php if (!$page->getSite()->getHideVotes()): ?>
<hr>
<h4><?php echo $this->page->getVoteCount();?> votes</h4>
<div class="table-container" id="vote-list">
<?php
$voteTable = $this->votes;

echo $this->partial(
    'partial/tables/default/table.phtml',
    array(
        'table' => $voteTable,
        'data' => array(),
    )
);
?>    
</div>
<?php endif; ?>


<div id="report-dialog" title="Enter correct information">
<?php $this->reportForm->setAttribute('action', '/page/report'); ?>
<?php $this->reportForm->prepare(); ?>
<?php echo $this->form()->openTag($this->reportForm); ?>
    <div id="report-error" hidden="" class="bg-danger"></div>
<?php echo $this->partial(
        'partial/pageReportFieldset.phtml',
        [
            'fieldset' => $this->reportForm->get('report'),
            'review' => false
        ]);
?>
<?php echo $this->form()->closeTag($this->reportForm); ?>

</div>