<?php 
    $table = $this->table;
    $col = $this->column; 
    $index = $this->index;
    $level = $this->level;
    $values = $this->values;
    $cols = $col->getSubColumns();
    $classes = ['responsive-table-cell', $this->prefix];
    if (!$cols->getCount()) {
        $classes[] = 'responsive-table-cell-data';
    }
    switch ($col->getKind()) {
        case \Application\Component\PaginatedTable\Column::PAGE:
            $classes[] = 'column-page';
            break;
        case \Application\Component\PaginatedTable\Column::USERS:
            $classes[] = 'column-users';
            break;
        case \Application\Component\PaginatedTable\Column::INDEX:
            $classes[] = 'column-index';
            break;
        case \Application\Component\PaginatedTable\Column::DATE:
            $classes[] = 'column-date';
            break;
        case \Application\Component\PaginatedTable\Column::DATE_TIME:
            $classes[] = 'column-date-time';
            break;                
    }    
?>
<div class="<?php echo implode($classes, ' ') ?>">    
    <?php if ($cols->getCount()): ?>
    <div class="responsive-table-column-group">
        <?php echo $this->partial('partial/tables/responsive/cells.phtml', [
            'table' => $table, 
            'columns' => $cols,
            'index' => $this->index,
            'values' => $this->values,
            'prefix' => $this->prefix,
            'level' => $level+1,
            'data' => $this->data]);
        ?>
    </div>
    <?php else: ?>
        <div class="responsive-table-value responsive-table-value-default">
        <?php
            echo $this->partial(
                $table->getBodyView(), 
                [
                    'index' => $index,
                    'column' => $col,
                    'row' => $values,                            
                    'data' => $this->data,
                    'collapsed' => false
                ]
            );          
        ?>
        </div>
        <div class="responsive-table-value responsive-table-value-collapsed">
        <?php
            echo $this->partial(
                $table->getBodyView(), 
                [
                    'index' => $index,
                    'column' => $col,
                    'row' => $values,                            
                    'data' => $this->data,
                    'collapsed' => true
                ]
            );          
        ?>
        </div>
    <?php endif; ?>
</div>

