<?php $this->headTitle('Pages'); ?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    function init()
    {
        scpper.tables.assignPaginatorEvents('#page-list', '/pages/pageList', {
            siteId: <?php echo $this->site->getId();?>,
            deleted: 0
        });
    }

    $(document).ready(init);
    
}());    

<?php $this->headScript()->captureEnd(); ?>
<span class="h1">
    <?php echo $this->partial('partial/site.phtml', ['site' => $this->site, 'link' => true]);?>
</span>
<?php if ($this->site->getLastUpdate()): ?>
<p class="small-text">
    Updated <?php echo $this->site->getLastUpdate()->format('Y-m-d H:i'); ?>
</p>
<?php endif; ?>
<h3>Pages (<?php echo $this->table->getPaginator()->getTotalItemCount();?> total)</h3>
<div class="table-container" id="page-list">
<?php
$table = $this->table;

echo $this->partial(
    'partial/tables/default/table.phtml', 
    [
        'table' => $table,
        'data' => ['siteId' => $this->site->getId()],
    ]
);    
?>
</div>