<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ScpperDB'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.gif'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/spinner.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 
                        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'));?>
        <!-- Scripts -->      
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6072049512866896",
    enable_page_level_ads: true
  });
</script>  
        <?php echo $this->headScript()                
            ->prependFile($this->basePath('js/scpper.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.blockUI.js'), 'text/javascript')
            ->prependFile($this->basePath('/js/jquery-ui/jquery-ui.min.js'), 'text/javascript') 
            ->prependFile($this->basePath('js/bootstrap.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/jquery.min.js'), 'text/javascript')
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/date.format.js'), 'text/javascript')            
            
        ; ?>       
        <script type="text/javascript">
        (function () {

        function init()
        {   
            // Prepare search form
            scpper.search.siteId = <?php echo $this->site->getId(); ?>;
            scpper.search.registerSearchAutocomplete();
            scpper.search.initSearchControl('.search-control');
            // Adjust content to the height of top navbar
            $(document).ready(function() {
                var contentPlacement = $('.scpper-navbar').position().top + $('.scpper-navbar').height()+10;
                $('body').css('margin-top', contentPlacement);
            });
        }

         $(document).ready(init);

        }()); 
        </script>
        <?php echo $this->headStyle() ?>
    </head>
    <body>
        <?php
            echo $this->navigation('navigation')
                ->menu()
                ->setPartial('partial/navbar.phtml');               
        ?>        
        <div class="container">
            <?php echo $this->content; ?>           
        </div> <!-- /container -->                
        <footer>
            <hr>
            <span class="small-text">
                Website by Alexander "FiftyNine" Krivopalov
            </span>                
            <br>                
            <span class="small-text">
                SCP Foundation and all related works were created by 
                <a href="http://scp-wiki.net">SCP creative community</a>  
                and are available under 
                <a href="https://creativecommons.org/licenses/by-sa/3.0/deed">CC BY-SA 3.0 license</a>
            </span>
        </footer>
        
        <?php echo $this->inlineScript() ?>        	        
    </body>
</html>