<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ScpperDB'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('js/date.format.js'), 'text/javascript')
            ->appendFile($this->basePath('js/scpper_layout.js'), 'text/javascript')
        ; ?>

    </head>
    <body>
        <?php
            echo $this->navigation('navigation')
                ->menu()
                ->setPartial('partial/navbar.phtml');               
        ?>
        <div class="container" id="main">
            <?php     /*
            echo $this->navigation('navigation')
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml'); */ ?>
            <div id="content">
                <?php echo $this->content; ?>
            </div>            
            <footer>
                <hr>
                <span class="small-text">
                    SCP Foundation and all related works were created by 
                    <a href="http://scp-wiki.net">SCP creative community</a>  
                    and are available under 
                    <a href="https://creativecommons.org/licenses/by-sa/3.0/deed">CC BY-SA 3.0 license</a>
                </span>
                <br>
                <span class="small-text">
                    Website by Alexander "FiftyNine" Krivopalov
                </span>
            </footer>
        </div> <!-- /container -->                
        <?php echo $this->inlineScript() ?>
    </body>
</html>
