<?php 
    $user = $this->user;
    $site = $this->site;
?>
<?php
$this->headScript()->appendFile('/js/scpper_charts.js');
$this->headScript()->appendFile('https://www.gstatic.com/charts/loader.js');
?>
<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function () {

    // Initialize global variables
    var userId = <?php echo $user->getId() ?>;
    var siteId = <?php echo $site->getWikidotId() ?>;

    function init()
    {
        scpper.tables.assignPaginatorEvents('#page-list', '/user/pageList', {siteId: siteId, userId: userId});
    }

    $(document).ready(init);    
    
    // Call google graphing API
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(function () {
        scpper.charts.rating.go('/user/ratingChart', {userId: userId, siteId: siteId}, 'user-rating-chart');
    });

}());

<?php $this->headScript()->captureEnd(); ?>
<p>
    <span class="h2">
        <a href="http://www.wikidot.com/user:info/<?php echo $user->getName();?>">
            <?php echo $this->user->getDisplayName();?>
        </a>
    </span>
    <br>
    on
    <a href="<?php echo $site->getUrl() ?>">
        <?php echo $site->getEnglishName() ?>
    </a>
    <br>
    <span class="small-text">
        Updated <?php echo $site->getLastUpdate()->format('Y-m-d H:i') ?>
    </span>
</p>
<hr>
<div id="user-top">
    <div id="user-summary">
        <?php $membership = $user->getMembershipOfSite($site->getWikidotId()); ?>        
        <?php if ($membership): ?>
            Joined: <strong><?php echo $membership->getJoinDate()->format('Y-m-d'); ?></strong>
        <?php else: ?>
            Not a member of this wiki
        <?php endif; ?>
        <br>
        <?php $activity = $user->getActivityOnSite($site->getWikidotId()); ?>
        <?php $isAuthor = $activity->getAuthorshipCount() > 0; ?>
        <?php if ($activity): ?>
            Last active: <strong><?php echo $activity->getLastActivity()->format('Y-m-d'); ?></strong>
            <br>
            Votes: <strong><?php echo $activity->getVoteCount(); ?></strong>
            <br>
            Revisions: <strong><?php echo $activity->getRevisionCount(); ?></strong>
            <br>
            Pages: <strong><?php echo $activity->getAuthorshipCount(); ?></strong>
            <br>
            <?php if ($isAuthor): ?>
                <?php $summary = $activity->getAuthorSummary(); ?>
                <ul>
                    <li>Originals: <strong><?php echo $summary->getOriginalCount(); ?></strong></li>
                    <li>Translations: <strong><?php echo $summary->getTranslationCount(); ?></strong></li>
                    <li>Average rating: <strong><?php echo number_format($summary->getAverageRating(), 1); ?></strong></li>
                    <li>Highest rating: <strong><?php echo $summary->getHighestRating(); ?></strong></li>
                    <li>Total: <strong><?php echo $summary->getTotalRating(); ?></strong></li>
                </ul>
                Rank: <strong>#<?php echo $activity->getAuthorRank()+1; ?></strong>
                <br>
            <?php endif; ?>        
        <?php endif; ?>
        <?php 
            $other = array();
            foreach ($user->getActivities() as $activity) {
                if ($activity->getSiteId() !== $site->getWikidotId()
                        && ($activity->getVoteCount() > 0 
                        || $activity->getRevisionCount() > 0 
                        || $activity->getAuthorshipCount() > 0)
                ) {
                    $other[$activity->getSiteId()] = array(
                        'activity' => $activity,
                        'membership' => $user->getMembershipOfSite($activity->getSiteId())
                    );
                }
            }
            foreach ($user->getMemberships() as $membership) {
                if ($membership->getSiteId() !== $site->getWikidotId() && !array_key_exists($membership->getSiteId(), $other)) {
                    $other[$membership->getSiteId()] = array(
                        'activity' => $user->getActivityOnSite($membership->getSiteId()),
                        'membership' => $membership
                    );
                }
            }   
        ?>
        <?php if (count($other) > 0): ?>
            Other:
            <ul>
            <?php foreach ($other as $i): ?>
                <li>
                    <a href="<?php echo $i['activity']->getSite()->getUrl(); ?>">
                        <?php echo $i['activity']->getSite()->getEnglishName(); ?>
                    </a>:
                    <?php printf(' %d votes, %d revisions, %d pages, ', $i['activity']->getVoteCount(), $i['activity']->getRevisionCount(), $i['activity']->getAuthorshipCount()); ?>
                    <?php if ($i['membership']): ?>
                        joined <?php echo $i['membership']->getJoinDate()->format('Y-m-d'); ?>
                    <?php else: ?>
                        not a member
                    <?php endif; ?>
                </li>                                   
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
    <div id="user-chart">
        <div class="chart-container" id="user-rating-chart">
        </div>
    </div>    
</div>
<hr>

<div class="container">
    <div class="row">
        <?php if ($user->getActivityOnSite($site->getWikidotId())->getVoteCount() > 0): ?>
        <div class="col-md-4">
            <h4>Favourite authors</h4>
            <ol>
                <?php foreach ($this->favs as $fav): ?>
                <li>
                    <a href="/user/<?php echo $fav[Application\Utils\DbConsts\DbViewAuthors::USERID] ?>">
                        <?php echo $fav[Application\Utils\DbConsts\DbViewAuthors::USERDISPLAYNAME] ?>
                    </a>
                     with 
                     <strong>
                    <?php
                        $negative = ((int)$fav['Votes']-(int)$fav['Rating'])/2;
                        $positive = (int)$fav['Votes']-$negative;
                        printf('%+d (%+d/%+d)', (int)$fav['Rating'], $positive, -$negative); 
                    ?>
                     </strong>
                </li>
                <?php endforeach; ?>
            </ol>        
        </div>
        <?php endif; ?>
        <?php if ($isAuthor): ?>
        <div class="col-md-4">
            <h4>Biggest fans</h4>
            <ol>
                <?php foreach ($this->fans as $fan): ?>
                <li>
                    <a href="/user/<?php echo $fan[Application\Utils\DbConsts\DbViewVotes::USERID] ?>">
                        <?php echo $fan[Application\Utils\DbConsts\DbViewVotes::USERDISPLAYNAME] ?>
                    </a>
                     with 
                     <strong>
                    <?php
                        $negative = ((int)$fan['Votes']-(int)$fan['Rating'])/2;
                        $positive = (int)$fan['Votes']-$negative;
                        printf('%+d (%+d/%+d)', (int)$fan['Rating'], $positive, -$negative); 
                    ?>
                     </strong>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <?php endif; ?>
    </div>
</div>

<h4><?php echo $this->pages->getPaginator()->getTotalItemCount();?> pages</h4>
<div class="table-container" id="page-list">
<?php
$table = $this->pages;

echo $this->partial(
    'partial/tables/table.phtml',
    array(
        'table' => $table,
        'data' => array(),
    )
);
?>
</div>

