<?php 
    $user = $this->user;
    $site = $this->site;
?>
<p>
    <span class="h2">
        <a href="http://www.wikidot.com/user:info/<?php echo $user->getName();?>">
            <?php echo $this->user->getDisplayName();?>
        </a>
    </span>
    <br>
    on
    <a href="<?php echo $site->getUrl() ?>">
        <?php echo $site->getEnglishName() ?>
    </a>
    <br>
    <span class="small-text">
        Updated <?php echo $site->getLastUpdate()->format('Y-m-d H:i') ?>
    </span>
</p>
<hr>
<div id="user-top">
    <div id="user-summary">
        <?php $membership = $user->getMembershipOfSite($site->getWikidotId()); ?>
        <?php if ($membership): ?>
            Joined: <strong><?php echo $membership->getJoinDate()->format('Y-m-d'); ?></strong>
        <?php else: ?>
            Not a member of this wiki
        <?php endif; ?>
        <br>
        <?php $activity = $user->getActivityOnSite($site->getWikidotId()); ?>
        <?php if ($activity): ?>
            Last active: <strong><?php echo $activity->getLastActivity()->format('Y-m-d'); ?></strong>
            <br>
            Votes: <strong><?php echo $activity->getVoteCount(); ?></strong>
            <br>
            Revisions: <strong><?php echo $activity->getRevisionCount(); ?></strong>
            <br>
            Pages: <strong><?php echo $activity->getAuthorshipCount(); ?></strong>
            <br>
            <?php if ($activity->getAuthorshipCount() > 0): ?>
                <?php $summary = $activity->getAuthorSummary(); ?>
                <ul>
                    <li>Originals: <strong><?php echo $summary->getOriginalCount(); ?></strong></li>
                    <li>Translations: <strong><?php echo $summary->getTranslationCount(); ?></strong></li>
                    <li>Average rating: <strong><?php echo number_format($summary->getAverageRating(), 1); ?></strong></li>
                    <li>Highest rating: <strong><?php echo $summary->getHighestRating(); ?></strong></li>
                    <li>Total: <strong><?php echo $summary->getTotalRating(); ?></strong></li>
                </ul>
                Rank: <strong><?php echo $activity->getAuthorRank()+1; ?></strong>
                <br>
            <?php endif; ?>        
        <?php endif; ?>
        <?php 
            $other = array();
            foreach ($user->getActivities() as $activity) {
                if ($activity->getSiteId() !== $site->getWikidotId()
                        && ($activity->getVoteCount() > 0 
                        || $activity->getRevisionCount() > 0 
                        || $activity->getAuthorshipCount() > 0)
                ) {
                    $other[$activity->getSiteId()] = array(
                        'activity' => $activity,
                        'membership' => $user->getMembershipOfSite($activity->getSiteId())
                    );
                }
            }
            foreach ($user->getMemberships() as $membership) {
                if ($membership->getSiteId() !== $site->getWikidotId() && !array_key_exists($membership->getSiteId(), $other)) {
                    $other[$membership->getSiteId()] = array(
                        'activity' => $user->getActivityOnSite($membership->getSiteId()),
                        'membership' => $membership
                    );
                }
            }   
        ?>
        <?php if (count($other) > 0): ?>
            Other wikis:
            <ul>
            <?php foreach ($other as $i): ?>
                <li>
                    <a href="<?php echo $i['activity']->getSite()->getUrl(); ?>">
                        <?php echo $i['activity']->getSite()->getEnglishName(); ?>
                    </a>:
                    <?php printf(' %d votes, %d revisions, %d pages, ', $i['activity']->getVoteCount(), $i['activity']->getRevisionCount(), $i['activity']->getAuthorshipCount()); ?>
                    <?php if ($i['membership']): ?>
                        joined <?php echo $i['membership']->getJoinDate()->format('Y-m-d'); ?>
                    <?php else: ?>
                        not a member
                    <?php endif; ?>
                </li>                                   
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
