<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        echo $this->index;
        break;
    case 'User':
        echo $this->partial('partial/user.phtml', array('user' => $row->getUser()));
        break;
    case 'Pages':
        echo $row->getPageCount();
        break;
    case 'Originals':
        echo $row->getOriginalCount();
        break;
    case 'Translations':
        echo $row->getTranslationCount();
        break;
    case 'Rating':
        echo $row->getTotalRating();
        break;
    case 'Average':
        echo number_format($row->getAverageRating(), 1);
        break;
    case 'Highest':
        echo $row->getHighestRating();
        break;
    default:;    
}
?> 