<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        if ($this->collapsed) {
            echo "#";
        }
        echo $this->index;
        break;
    case 'User':
        $deleted = $row[\Application\Utils\DbConsts\DbViewRevisions::USERDELETED]; 
        if ($deleted) { echo "<del>"; }
        echo '<a href="';
        printf('/user/%d', $row[\Application\Utils\DbConsts\DbViewRevisions::USERID]);
        echo '">';
        echo $this->escapeHtml($row[\Application\Utils\DbConsts\DbViewRevisions::USERDISPLAYNAME]);
        echo "</a>";
        if ($deleted) { echo "</del>";}
        break;
    case 'Revisions':
        if ($this->collapsed): ?>
            <span class="glyphicon glyphicon-edit"></span>
        <?php endif;        
        echo $row['Revisions'];
        break;
    case '%':
        if ($this->collapsed): ?>
            <b>%</b>&nbsp;
        <?php endif;        
        echo number_format($row['Revisions']/$this->data['total']*100, 2);
        break;
    default:;    
}
?> 