<?php 
    $i=1;
    foreach ($this->rows as $member): 
?>
<tr>
    <td><?php echo $this->rows->getAbsoluteItemNumber($i); $i++; ?></td>
    <td>
        <?php echo $this->partial('partial/user.phtml', array('user' => $member->getUser())); ?>
    </td>
    <td><?php echo $member->getActivity()->getVoteCount(); ?></td>
    <td><?php echo $member->getActivity()->getRevisionCount(); ?></td>
    <td><?php echo $member->getActivity()->getAuthorshipCount(); ?></td>
    <td><?php if ($member->getActivity()->isActive()) {echo '&check;';} ?></td>    
    <td>
        <?php 
            if ($member->getJoinDate() != null) {
                echo $member->getJoinDate()->format('Y-m-d'); 
            }
        ?>
    </td>
</tr>
<?php endforeach; ?>