<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        echo $this->index;
        break;
    case 'User':
        echo $this->partial('partial/user.phtml', array('user' => $row->getUser()));
        break;
    case 'Votes':
        echo $row->getActivity()->getVoteCount();
        break;
    case 'Revisions':
        echo $row->getActivity()->getRevisionCount();
        break;
    case 'Pages':
        echo $row->getActivity()->getAuthorshipCount();
        break;
    case 'Active':
        if ($row->getActivity()->isActive()) {echo '&check;';}
        break;
    case 'Joined':
        if ($row->getJoinDate() != null) {
            echo $row->getJoinDate()->format('Y-m-d'); 
        }
        break;
    default:;    
}
?> 