<?php 
    $i=1;
    foreach ($this->rows as $page): 
?>
<tr>
    <td><?php echo $this->rows->getAbsoluteItemNumber($i); $i++; ?></td>
    <td>
        <?php echo $this->partial('partial/page.phtml', array('page' => $page)); ?>
    </td>
    <td><?php echo $page->getCleanRating(); ?></td>
<!--    <td><?php echo $page->getContributorRating(); ?></td>
    <td><?php echo $page->getAdjustedRating(); ?></td> -->
    <td>        
        <?php 
            $stars = round($page->getWilsonScore()*10);            
            for ($i=0; $i<5; $i++):
                if ($stars >= 2):
        ?>
                    <img src="/img/FullStar.png" alt="Star" class="rating-image">
        <?php
                    $stars-=2;
                elseif ($stars >= 1):
        ?>
                    <img src="/img/HalfStar.png" alt="Half" class="rating-image">
        <?php                    
                    $stars--;
                else:
        ?>
                    <img src="/img/EmptyStar.png" alt="Empty" class="rating-image">
        <?php                           
                endif;
            endfor;
        ?>
    </td>    
    <td><?php echo \Application\Utils\PageStatus::getDescription($page->getStatus()); ?></td>
    <td><?php echo \Application\Utils\PageKind::getDescription($page->getKind()); ?></td>
    <td><?php echo $page->getCreationDate()->format('Y-m-d'); ?></td>
    <td>
        <?php 
            $authors = $page->getAuthors();
            $one = 1 === count($authors);
        ?>
        <?php foreach ($authors as $author): ?>
            <?php echo $this->partial('partial/user.phtml', array('user' => $author->getUser())); ?>
            <?php 
                if (!$one || $author->getRole() !== \Application\Utils\AuthorRole::AUTHOR) {
                    printf("&nbsp;(%s)", \Application\Utils\AuthorRole::getDescription($author->getRole()));
                }
            ?>
            <br>
        <?php endforeach; ?>
    </td>
</tr>
<?php endforeach; ?>