<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        echo $this->index;
        break;
    case 'Branch':
        echo strtoupper($row->getSite()->getShortName());
        break;
    case 'Page':
        echo $this->partial('partial/page.phtml', array('page' => $row));
        break;
    case 'Total':
        echo $row->getCleanRating();
        break;
    case 'Contributor':
        echo $row->getContributorRating();
        break;
    case 'Adjusted':
        echo $row->getAdjustedRating();
        break;
    case 'Wilson':
        echo number_format($row->getWilsonScore()*100, 2).'%';
        break;
    case 'Status':
        echo \Application\Utils\PageStatus::getDescription($row->getStatus());
        break;
    case 'Kind':
        echo \Application\Utils\PageKind::getDescription($row->getKind());
        break;
    case 'Posted':
        echo $row->getCreationDate()->format('Y-m-d');
        break;
    case 'Authors':
        echo $this->partial('partial/authors.phtml', ['authors' => $row->getAuthors()]);
        break;
    default:;    
}
?> 