<?php  
    $table = $this->table; 
    $cols = $table->getColumns();
?>
<table class="table table-striped 
    <?php 
        if ($table->isPreview()) {
            echo "table-preview";
        } else {
            echo "table-sortable";             
        } 
    ?>
    "
>
    <?php
        $colArray = $cols->toArray();
        $maxLevel = $cols->getMaxNestedLevel();
    ?>
    <?php for ($level=0; $level<count($colArray); $level++): ?>
    <?php $levelCols = $colArray[$level]; ?>
    <tr>
        <?php foreach ($levelCols as $col): ?>
        <th 
            <?php 
            $thisOrder = $col->canOrder() && ($cols->getOrderBy() === $col);
            $classes = array();
            $attributes = array();
            if ($col->canOrder()) {
                $classes[] = 'can-order';
                $attributes[] = 'data-name="'.$col->getOrderName().'"';
                if ($thisOrder) {
                    $classes[] = 'ordered';
                    $attributes[] = 'data-ascending="'.($cols->isAscending()?'1':'0').'"';
                } else {
                    $attributes[] = 'data-ascending="'.($col->isDefaultAscending()?'0':'1').'"';
                }
            }
            $colspan = $col->getColSpan();
            if ($colspan > 1) {
                $attributes[] = 'colspan="'.$colspan.'"';
            }
            if ($col->getSubColumns()->getCount()) {
                $rowspan = 1;
            } else {
                $rowspan = $maxLevel - $level;
            }
            if ($rowspan > 1) {
                $attributes[] = 'rowspan="'.$rowspan.'"';
            }
            switch ($col->getKind()) {
                case \Application\Component\PaginatedTable\Column::PAGE:
                    $classes[] = 'column-page';
                    break;
                case \Application\Component\PaginatedTable\Column::USERS:
                    $classes[] = 'column-users';
                    break;
                case \Application\Component\PaginatedTable\Column::INDEX:
                    $classes[] = 'column-index';
                    break;
                case \Application\Component\PaginatedTable\Column::DATE:
                    $classes[] = 'column-date';
                    break;
                case \Application\Component\PaginatedTable\Column::DATE_TIME:
                    $classes[] = 'column-date-time';
                    break;                
            }            
            if ($classes) {
                echo 'class="'.implode(' ', $classes).'" ';
            }
            foreach ($attributes as $attr) {
                echo $attr.' ';
            }
            ?>
        >
            <?php if ($col->getTooltip()): ?>
            <abbr title="<?php echo $col->getTooltip(); ?>">
            <?php endif; ?>            
            <?php
                echo $col->getName(); 
                if ($thisOrder) {
                    if ($cols->isAscending()) {
                        echo "&nbsp;&UpArrow;";
                    } else {
                        echo "&nbsp;&DownArrow;";
                    }
                }
            ?>
            <?php if ($col->getTooltip()): ?>
            </abbr>
            <?php endif; ?>                            
        </th>           
        <?php endforeach;?>
    </tr>
    <?php endfor; ?>
    <?php 
        echo $this->partial(
            $table->getBodyView(), 
            array(
                'rows' => $table->getPaginator(),
                'data' => $this->data
            )
        ); 
    ?>
</table>
<?php 
    if (!$table->isPreview()) {
        echo $this->paginationControl($table->getPaginator(), 'Sliding', 'partial/paginator'); 
    }
?>