<?php  
    $table = $this->table; 
    $cols = $table->getColumns();
?>
<table class="table table-striped 
    <?php 
        if ($table->isPreview()) {
            echo "table-preview";
        } else {
            echo "table-sortable";             
        } 
    ?>
    "
>
    <tr>
        <?php foreach ($cols as $index => $col): ?>
        <th 
            <?php 
            $thisOrder = $col->canOrder() && ($cols->getOrderBy() === $index);
            $classes = array();
            $attributes = array();
            if ($col->canOrder()) {
                $classes[] = 'can-order';
                $attributes[] = 'data-name="'.$col->getOrderName().'"';
                if ($thisOrder) {
                    $classes[] = 'ordered';
                    $attributes[] = 'data-ascending="'.($cols->isAscending()?'1':'0').'"';
                } else {
                    $attributes[] = 'data-ascending="'.($col->isDefaultAscending()?'0':'1').'"';
                }
            }
            if ($classes) {
                echo 'class="'.implode(' ', $classes).'" ';
            }
            foreach ($attributes as $attr) {
                echo $attr.' ';
            }
            ?>
        >
            <?php if ($col->getTooltip()): ?>
            <abbr title="<?php echo $col->getTooltip(); ?>">
            <?php endif; ?>            
            <?php
                echo $col->getName(); 
                if ($thisOrder) {
                    if ($cols->isAscending()) {
                        echo "&nbsp;&UpArrow;";
                    } else {
                        echo "&nbsp;&DownArrow;";
                    }
                }
            ?>
            <?php if ($col->getTooltip()): ?>
            </abbr>
            <?php endif; ?>                            
        </th>           
        <?php endforeach;?>
    </tr>
    <?php 
        echo $this->partial(
            $table->getBodyView(), 
            array(
                'rows' => $table->getPaginator(),
                'data' => $this->data
            )
        ); 
    ?>
</table>
<?php 
    if (!$table->isPreview()) {
        echo $this->paginationControl($table->getPaginator(), 'Sliding', 'partial/paginator'); 
    }
?>