<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        if ($this->collapsed) {
            echo "#";
        }        
        echo $this->index;
        break;
    case 'Page':
        if ($this->collapsed): ?>
            <span class="glyphicon glyphicon-file"></span>
        <?php endif;                
        echo $this->partial('partial/page.phtml', ['page' => $row->getPage(), 'link' => true]);
        break;
    case 'Authors':
        echo $this->partial('partial/authors.phtml', ['authors' => $row->getPage()->getAuthors(), 'collapsed' => $this->collapsed]);
        break;
    case 'Vote':
        if ($row->getValue() > 0) {echo '+';} else {echo '-';}
        break;
    case 'Date':
        echo $row->getDateTime()->format('Y-m-d');
        break;
    default:;    
}
?> 