<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        echo $this->index;
        break;
    case 'User':
        echo $this->partial('partial/user.phtml', array('user' => $row));
        break;
    case 'Membership':
        $res = [];
        foreach ($row->getMemberships() as $membership) {
            $res[] = strtoupper($membership->getSite()->getShortName());
        }
        echo implode(', ', $res);
        break;
    default:;    
}
?>
