<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        if ($this->collapsed) {
            echo "#";
        }        
        echo $this->index;
        break;
    case 'User':
        $deleted = $row[\Application\Utils\DbConsts\DbViewVotes::USERDELETED]; 
        if ($deleted) { echo "<del>"; }
        echo '<a href="';
        printf('/user/%d', $row[\Application\Utils\DbConsts\DbViewVotes::USERID]);
        echo '">';
        echo $this->escapeHtml($row[\Application\Utils\DbConsts\DbViewVotes::USERDISPLAYNAME]);
        echo "</a>";
        if ($deleted) { echo "</del>";}
        break;
    case 'Votes':
        if ($this->collapsed): ?>
            <span class="glyphicon glyphicon-sort"></span>
        <?php endif;        
        echo $row['Votes'];
        break;
    case 'Positive':
        if ($this->collapsed): ?>
            <span class="glyphicon glyphicon-plus"></span>
        <?php endif;        
        echo ($row['Votes']+$row['Sum'])/2;
        break;
    case 'Negative':
        if ($this->collapsed): ?>
            <span class="glyphicon glyphicon-minus"></span>
        <?php endif;        
        echo ($row['Votes']-$row['Sum'])/2;
        break;
    default:;    
}
?> 