<?php 
$row = $this->row;
switch($this->column->getName()) {
    case '#':
        echo $this->index;
        break;
    case 'User':
        echo $this->partial('partial/user.phtml', array('user' => $row->getUser()));
        break;
    case 'Page':
        echo $this->partial('partial/page.phtml', array('page' => $row->getPage()));
        break;
    case 'Vote':
        if ($row->getValue() > 0) {echo '+';} else {echo '-';}
        break;
    case 'Member':
        if ($row->getFromMember()) {echo '&check;';}
        break;
    case 'Contributor':
        if ($row->getFromContributor()) {echo '&check;';}
        break;
    case 'Active':
        if ($row->getFromActive()) {echo '&check;';}
        break;
    case 'Date':
        echo $row->getDateTime()->format('Y-m-d');
        break;        
    default:;    
}
?> 


