<?php
$this->headScript()->appendFile('/js/scpper_charts.js');
$this->headScript()->appendFile('/js/jquery-ui/jquery-ui.min.js');
$this->headScript()->appendFile('https://www.gstatic.com/charts/loader.js');
$this->headLink()->prependStylesheet($this->basePath('css/jquery-ui.min.css'));

$form = $this->intervalForm;
$form->setAttribute('action', $this->url('changes'));
//$form->setAttribute('method', 'GET');
$fromDate = $form->get('from-date');
$toDate = $form->get('to-date');
$submit = $form->get('submit');
$submit->setValue('Show');
$site = $this->site;
$this->headTitle(sprintf('Changes from %s to %s', $fromDate->getValue(), $toDate->getValue()));
?>

<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function() {

    // Initialize global variables
    var chartsData = {};
    chartsData.siteId = <?php echo $site->getId(); ?>;
    chartsData.fromDate = "<?php echo $fromDate->getValue(); ?>";
    chartsData.toDate = "<?php echo $toDate->getValue(); ?>";
    // Variables for pagination
    paginatorData = $.extend({page: 1, perPage: 10}, chartsData);

    function activateTab(tab, loader)
    {
        $('.activity-tabs-row>.activity-tab').removeClass('active');
        $('.activity-data').addClass('collapse');
        $('.activity-tabs-row>'+tab).addClass('active');
        $(tab+'+.activity-data').toggleClass('collapse').show();
        loader(chartsData);
    }
    
    function init()
    {
        $('#show-members').on('click', {container: "#members-list", url: "/changes/members", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-pages').on('click', {container: "#pages-list", url: "/changes/pages", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-editors').on('click', {container: "#editors-list", url: "/changes/editors", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-voters').on('click', {container: "#voters-list", url: "/changes/voters", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);    
        $('.datepicker').datepicker({autoSize: true, dateFormat: "yy-mm-dd", maxDate: "<?php echo $site->getLastUpdate()->format('Y-m-d');?>"});
        $('.activity-tabs-stack>.activity-tab').on('click', null, function(event) {$(this).toggleClass('active');});
        $('.activity-tabs-row>.activity-tab-users').on('click', null, function(event) {activateTab('.activity-tab-users', scpper.charts.changes.drawMemberCharts)});
        $('.activity-tabs-row>.activity-tab-pages').on('click', null, function(event) {activateTab('.activity-tab-pages', scpper.charts.changes.drawPageCharts)});
        $('.activity-tabs-row>.activity-tab-revisions').on('click', null, function(event) {activateTab('.activity-tab-revisions', scpper.charts.changes.drawRevisionCharts)});
        $('.activity-tabs-row>.activity-tab-votes').on('click', null, function(event) {activateTab('.activity-tab-votes', scpper.charts.changes.drawVoteCharts)});
        $('.activity-tabs-stack>.activity-tab-users').on('click', null, function(event) {scpper.charts.changes.drawMemberCharts(chartsData)});
        $('.activity-tabs-stack>.activity-tab-pages').on('click', null, function(event) {scpper.charts.changes.drawPageCharts(chartsData)});
        $('.activity-tabs-stack>.activity-tab-revisions').on('click', null, function(event) {scpper.charts.changes.drawRevisionCharts(chartsData)});
        $('.activity-tabs-stack>.activity-tab-votes').on('click', null, function(event) {scpper.charts.changes.drawVoteCharts(chartsData)});
        if (window.innerWidth >= 768) {
            activateTab('.activity-tab-users', scpper.charts.changes.drawMemberCharts);
        }        
    }

    $(document).ready(init);

    // Call google graphing API
    google.charts.load('current', {packages: ['corechart']});
    // google.charts.setOnLoadCallback(function () {scpper.charts.changes.go(chartsData);});
}());

<?php $this->headScript()->captureEnd(); ?>

<?php
    $form->prepare();
    echo $this->form()->openTag($form);
?>
    <div id="date-interval-form">
        <div id="date-interval-inputs">
            <?php echo $this->formElement($fromDate); ?>
            <span id="date-interval-separator">–</span>
            <?php echo $this->formElement($toDate); ?>
        </div>
        <?php echo $this->formElement($submit); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>

<?php

function printInfoLabel($data)
{
    foreach ($data['header'] as $name => $number) {
        echo "<h4>$number total</h4>";
    }
    if (count($data['list']) > 0) {
        echo '<ul class="list-unstyled">';
        foreach ($data['list'] as $name => $number) {
            echo "<li>$number $name</li>";
        }
        echo '</ul>';    
    }
}

?>

<nav class="activity-tabs activity-tabs-row">
    <div class="activity-tab activity-tab-users"><a href="javascript:;">Members</a></div>
    <div class="activity-tab activity-tab-pages"><a href="javascript:;">Pages</a></div>
    <div class="activity-tab activity-tab-revisions"><a href="javascript:;">Revisions</a></div>
    <div class="activity-tab activity-tab-votes"><a href="javascript:;">Votes</a></div>
</nav>

<nav class="activity-tabs activity-tabs-stack bottom-buffer">
    <!-- USERS -->
    <div class="activity-tab activity-tab-users">
        <a href="javascript:;" data-toggle="collapse" data-target=".activity-users">
            Members
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-up"></span>
        </a>
    </div>    
    <div class="activity-data activity-users collapse">
        <div class="info-box">
            <?php printInfoLabel($this->members); ?>
        </div>
        <div class='activity-charts'>
            <div class="chart-container top-buffer-small" id="members-joined"></div>
            <div class="chart-container top-buffer-small" id="members-total"></div>
        </div>
        <div class="table-container top-buffer-small" id="members-list">
            <?php 
                $membersTable = $this->members['table'];
                echo $this->partial(
                    'partial/tables/default/table.phtml', 
                    array(
                        'table' => $membersTable,
                        'data' => array('siteId' => $site->getId()),
                    )
                );
            ?>
            <div class="text-center">
                <a class="btn btn-default btn-table" id="show-members" href="javascript:;" role="button">Show more</a>               
            </div>
        </div>
    </div>
    <!-- PAGES -->
    <div class="activity-tab activity-tab-pages">
        <a href="javascript:;" data-toggle="collapse" data-target=".activity-pages">
            Pages
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-up"></span>            
        </a>
    </div>    
    <div class="activity-data activity-pages collapse">
        <div class="info-box">
            <?php printInfoLabel($this->pages); ?>
        </div>
        <div class='activity-charts'>
            <div class="chart-container top-buffer-small" id="pages-created"></div>
            <div class="chart-container top-buffer-small" id="pages-total"></div>
        </div>
        <div class="table-container top-buffer-small" id="pages-list">
            <?php 
                $pagesTable = $this->pages['table'];
                echo $this->partial(
                    'partial/tables/default/table.phtml', 
                    array(
                        'table' => $pagesTable,
                        'data' => array(),
                    )
                );
            ?>
            <div class="text-center">
                <a class="btn btn-default btn-table" id="show-pages" href="javascript:;" role="button">Show more</a>               
            </div>
        </div>
    </div>
    <!-- REVISIONS -->
    <div class="activity-tab activity-tab-revisions">
        <a href="javascript:;" data-toggle="collapse" data-target=".activity-revisions">
            Revisions
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-up"></span>            
        </a>
    </div>    
    <div class="activity-data activity-revisions collapse">       
        <div class="info-box">
            <?php printInfoLabel($this->revisions); ?>
        </div>
        <div class='activity-charts'>
            <div class="chart-container top-buffer-small" id="revisions-created"></div>
            <div class="chart-container top-buffer-small" id="revisions-total"></div>
        </div>
        <div class="table-container top-buffer-small" id="editors-list">
            <?php 
                $revisionsTable = $this->revisions['table'];
                echo $this->partial(
                    'partial/tables/default/table.phtml', 
                    array(
                        'table' => $revisionsTable,
                        'data' => array(
                            'total' => $this->revisions['header']['revisions']
                        ),
                    )
                );
            ?>
            <div class="text-center">
                <a class="btn btn-default btn-table" id="show-editors" href="javascript:;" role="button">Show more</a>               
            </div>
        </div>    
    </div>
    <!-- VOTES -->
    <div class="activity-tab activity-tab-votes">
        <a href="javascript:;" data-toggle="collapse" data-target=".activity-votes">
            Votes
            <span class="glyphicon glyphicon-menu-down"></span>
            <span class="glyphicon glyphicon-menu-up"></span>            
        </a>
    </div>
    <div class="activity-data activity-votes collapse">                    
        <div class="info-box">
            <?php printInfoLabel($this->votes); ?>
        </div>
        <div class='activity-charts'>
            <div class="chart-container top-buffer-small" id="votes-cast"></div>
            <div class="chart-container top-buffer-small" id="votes-total"></div>
        </div>
        <div class="table-container top-buffer-small" id="voters-list">
            <?php 
                $votersTable = $this->votes['table'];
                echo $this->partial(
                    'partial/tables/default/table.phtml', 
                    array(
                        'table' => $votersTable,
                        'data' => array(
                        ),
                    )
                );
            ?>
            <div class="text-center">
                <a class="btn btn-default btn-table" id="show-voters" href="javascript:;" role="button">Show more</a>               
            </div>
        </div>
    </div>
</nav>
<div id="basic-table-error-row" hidden>
    <table>
    <tr>
        <td colspan="100">
            Failed to retrieve data
        </td>
    </tr>
    </table>
</div>

<div id="responsive-table-error-row" hidden>
    <div class="responsive-table-row responsive-table-data">
        Failed to retrieve data
    </div>
</div>