<?php
$this->headScript()->appendFile('/js/scpper_charts.js');
$this->headScript()->appendFile('/js/jquery-ui/jquery-ui.min.js');
$this->headScript()->appendFile('https://www.gstatic.com/charts/loader.js');
$this->headLink()->prependStylesheet($this->basePath('css/jquery-ui.min.css'));

$form = $this->intervalForm;
$form->setAttribute('action', $this->url('changes'));
//$form->setAttribute('method', 'GET');
$fromDate = $form->get('from-date');
$toDate = $form->get('to-date');
$submit = $form->get('submit');
$submit->setValue('Show');
$site = $this->site;
$this->headTitle(sprintf('Changes from %s to %s', $fromDate->getValue(), $toDate->getValue()));
?>

<?php $this->headScript()->captureStart(); ?>

// Anonymous self-executing function not to clutter global scope with temporary stuff
(function() {

    // Initialize global variables
    var chartsData = {};
    chartsData.siteId = <?php echo $site->getId(); ?>;
    chartsData.fromDate = "<?php echo $fromDate->getValue(); ?>";
    chartsData.toDate = "<?php echo $toDate->getValue(); ?>";
    // Variables for pagination
    paginatorData = $.extend({page: 1, perPage: 10}, chartsData);

    function init()
    {
        $('#show-members').on('click', {container: "#members-list", url: "/changes/members", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-pages').on('click', {container: "#pages-list", url: "/changes/pages", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-editors').on('click', {container: "#editors-list", url: "/changes/editors", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);
        $('#show-voters').on('click', {container: "#voters-list", url: "/changes/voters", payload: paginatorData}, scpper.tables.fetchPaginatorFirst);    
        $('.datepicker').datepicker({autoSize: true, dateFormat: "yy-mm-dd", maxDate: "<?php echo $site->getLastUpdate()->format('Y-m-d');?>"});
    }

    $(document).ready(init);

    // Call google graphing API
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(function () {scpper.charts.changes.go(chartsData);});
}());

<?php $this->headScript()->captureEnd(); ?>
<div class="form-inline">
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
        <div class="form-group">
            <?php echo $this->formElement($fromDate); ?>
        </div>
    –
        <div class="form-group">
            <?php echo $this->formElement($toDate); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formElement($submit); ?>
        </div>
    <?php $this->form()->closeTag(); ?>
</div>
<?php

function printInfoLabel($data)
{
    foreach ($data['header'] as $name => $number) {
        echo "<h3>$number $name</h3>";
    }
    if (count($data['list']) > 0) {
        echo '<hr>';
        echo '<ul class="list-unstyled">';
        foreach ($data['list'] as $name => $number) {
            echo "<li>$number $name</li>";
        }
        echo '</ul>';    
    }
}

?>
<!-- USERS -->
<h1>Users</h1>
<hr>
<div class="container top-buffer">
    <div class="row">
        <div class="col-md-2 info-box background-green">
            <?php printInfoLabel($this->members); ?>
        </div>
        <div class="col-md-8">
            <div class="chart-container" id="members-joined">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="chart-container" id="members-total">                
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="table-container" id="members-list">
                <?php 
                    $membersTable = $this->members['table'];
                    echo $this->partial(
                        'partial/tables/table.phtml', 
                        array(
                            'table' => $membersTable,
                            'data' => array('siteId' => $site->getId()),
                        )
                    );
                ?>
                <div class="text-center">
                    <a class="btn btn-default btn-table" id="show-members" href="javascript:;" role="button">Show more</a>               
                </div>
            </div>
        </div>
    </div>    
</div>
<!-- PAGES -->
<h1>Pages</h1>
<hr>
<div class="container top-buffer">
    <div class="row">
        <div class="col-md-2 info-box background-blue">
            <?php printInfoLabel($this->pages); ?>
        </div>
        <div class="col-md-8">
            <div class="chart-container" id="pages-created">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="chart-container" id="pages-total">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="table-container" id="pages-list">
                <?php 
                    $pagesTable = $this->pages['table'];
                    echo $this->partial(
                        'partial/tables/table.phtml', 
                        array(
                            'table' => $pagesTable,
                            'data' => array(),
                        )
                    );
                ?>
                <div class="text-center">
                    <a class="btn btn-default btn-table" id="show-pages" href="javascript:;" role="button">Show more</a>               
                </div>
            </div>
        </div>
    </div>        
</div>
<!-- REVISIONS -->
<h1>Revisions</h1>
<hr>
<div class="container top-buffer">
    <div class="row">
        <div class="col-md-2 info-box background-red">
            <?php printInfoLabel($this->revisions); ?>
        </div>
        <div class="col-md-8">
            <div class="chart-container" id="revisions-created">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="chart-container" id="revisions-total">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="table-container" id="editors-list">
                <?php 
                    $revisionsTable = $this->revisions['table'];
                    echo $this->partial(
                        'partial/tables/table.phtml', 
                        array(
                            'table' => $revisionsTable,
                            'data' => array(
                                'total' => $this->revisions['header']['revisions']
                            ),
                        )
                    );
                ?>
                <div class="text-center">
                    <a class="btn btn-default btn-table" id="show-editors" href="javascript:;" role="button">Show more</a>               
                </div>
            </div>
        </div>
    </div>            
</div>
<!-- VOTES -->
<h1>Votes</h1>
<hr>
<div class="container top-buffer">
    <div class="row">
        <div class="col-md-2 info-box background-orange">
            <?php printInfoLabel($this->votes); ?>
        </div>
        <div class="col-md-8">
            <div class="chart-container" id="votes-cast">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="chart-container" id="votes-total">
            </div>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-8 col-md-offset-2">
            <div class="table-container" id="voters-list">
                <?php 
                    $votersTable = $this->votes['table'];
                    echo $this->partial(
                        'partial/tables/table.phtml', 
                        array(
                            'table' => $votersTable,
                            'data' => array(
                            ),
                        )
                    );
                ?>
                <div class="text-center bottom-buffer">
                    <a class="btn btn-default btn-table" id="show-voters" href="javascript:;" role="button">Show more</a>               
                </div>
            </div>
        </div>
    </div>                
</div>
<div id="table-error-row" hidden>
    <table>
    <tr>
        <td colspan="100">
            Failed to retrieve data
        </td>
    </tr>
    </table>
</div>